apiVersion: v1
kind: Pod
metadata:
  name: easyfl-server
  namespace: easyfl
  labels:
    app: easyfl-server
spec:
  containers:
  - name: easyfl-server
    image: abh15/easyfl-server
    imagePullPolicy: IfNotPresent
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    args: ["--is-remote", "True", "--local-port", "23501", "--tracker-addr", "easyfl-tracker-svc.easyfl:12666"]
    ports:
    - containerPort: 23501
