apiVersion: v1
kind: Pod
metadata:
  name: easyfl-tracker
  namespace: easyfl
  labels:
    app: easyfl-tracker
spec:
  containers:
  - name: easyfl-tracker
    image: abh15/easyfl-tracker:latest
    env:
    - name: PYTHONUNBUFFERED
      value: "1"
    args: ["--local-port", "12666"]
    ports:
    - containerPort: 12666
